version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend.Dockerfile
      args:
        - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./apps/frontend:/app/apps/frontend
      - /app/apps/frontend/node_modules
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_BACKEND_API_URL=http://localhost:8000
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: ./docker/backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./apps/backend:/app
      - ./apps/backend/logs:/app/logs
    environment:
      - ENVIRONMENT=development
      - HOST=0.0.0.0
      - PORT=8000
      - FRONTEND_URL=http://localhost:3000
    env_file:
      - ./apps/backend/.env
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

networks:
  default:
    driver: bridge 