[build]
publish = "apps/frontend/.next"
command = "npm run build"

[[plugins]]
package = "@netlify/plugin-nextjs"

[dev]
framework = "next"
directory = "apps/frontend"
targetPort = 3000
port = 8888
autoLaunch = true