[build]
publish = "apps/frontend/.next"
command = "npm run build"

[[plugins]]
package = "@netlify/plugin-nextjs"

[dev]
framework = "next"
directory = "apps/frontend"
targetPort = 3000
autoLaunch = true

[build.environment]
NODE_VERSION = "18"
NPM_FLAGS = "--version"

[[redirects]]
from = "/api/*"
to = "https://web-app-cizo.onrender.com/api/:splat"
status = 200
force = true